-- Addon:	     ClassicHunterPetInfo
-- Author:	     Spielstein@Curse

if select(2, UnitClass("player")) ~= "HUNTER" then
    --return
end

-- HTML-Parsing info for sublime:
-- https://www.wow-petopia.com/classic/attackspeed.php
--
-- RegEx:
--    .*npc=(\d+)'>([\w\s'-]+)</a> \(([\w\s'-]+), ([\d-]+), ([\w\s'-]+).*
-- FormattedReplacement:
--    [$1] = { ["attack_speed"] = XXXXX, ["name"] = "$2", ["family"] = "$3", ["level_range"] = "$4", ["area"] = "$5" },

-- Levelrange formatting info for sublime:
-- RegEx 1:
--    \["level_range"\] = "(\d+)-(\d+)",
-- FormattedReplacement 1:
--    ["min_level"] = $1,\n\t\t["max_level"] = $2,
-- RegEx 2:
--    \["level_range"\] = "(\d+)",
-- FormattedReplacement 2:
--    ["min_level"] = $1,\n\t\t["max_level"] = $1,



ClassicHunterPetInfo.PET_INFORMATION = {
	[1509] = {
		["attack_speed"] = 1.0,
		["name"] = "Ragged Scavenger",
		["family"] = "Wolf",
		["min_level"] = 2,
		["max_level"] = 3,
		["area"] = "Tirisfal Glades",
	},
	[1505] = {
		["attack_speed"] = 1.0,
		["name"] = "Night Web Spider",
		["family"] = "Spider",
		["min_level"] = 3,
		["max_level"] = 4,
		["area"] = "Tirisfal Glades",
	},
	[30] = {
		["attack_speed"] = 1.0,
		["name"] = "Forest Spider",
		["family"] = "Spider",
		["min_level"] = 5,
		["max_level"] = 6,
		["area"] = "Elwynn Forest",
	},
	[1994] = {
		["attack_speed"] = 1.0,
		["name"] = "Githyiss the Vile",
		["family"] = "Spider",
		["min_level"] = 5,
		["max_level"] = 5,
		["area"] = "Teldrassil",
	},
	[2958] = {
		["attack_speed"] = 1.0,
		["name"] = "Prairie Wolf",
		["family"] = "Wolf",
		["min_level"] = 5,
		["max_level"] = 6,
		["area"] = "Mulgore",
	},
	[1688] = {
		["attack_speed"] = 1.0,
		["name"] = "Night Web Matriarch",
		["family"] = "Spider",
		["min_level"] = 5,
		["max_level"] = 5,
		["area"] = "Tirisfal Glades",
	},
	[1138] = {
		["attack_speed"] = 1.0,
		["name"] = "Snow Tracker Wolf",
		["family"] = "Wolf",
		["min_level"] = 6,
		["max_level"] = 7,
		["area"] = "Dun Morogh",
	},
	[1922] = {
		["attack_speed"] = 1.0,
		["name"] = "Gray Forest Wolf",
		["family"] = "Wolf",
		["min_level"] = 7,
		["max_level"] = 8,
		["area"] = "Elwynn Forest",
	},
	[1131] = {
		["attack_speed"] = 1.0,
		["name"] = "Winter Wolf",
		["family"] = "Wolf",
		["min_level"] = 7,
		["max_level"] = 8,
		["area"] = "Dun Morogh",
	},
	[1999] = {
		["attack_speed"] = 1.0,
		["name"] = "Webwood Venomfang",
		["family"] = "Spider",
		["min_level"] = 7,
		["max_level"] = 8,
		["area"] = "Teldrassil",
	},
	[2959] = {
		["attack_speed"] = 1.0,
		["name"] = "Prairie Stalker",
		["family"] = "Wolf",
		["min_level"] = 7,
		["max_level"] = 8,
		["area"] = "Mulgore",
	},
	[3110] = {
		["attack_speed"] = 1.0,
		["name"] = "Dreadmaw Crocolisk",
		["family"] = "Crocolisk",
		["min_level"] = 9,
		["max_level"] = 11,
		["area"] = "Durotar",
	},
	[1133] = {
		["attack_speed"] = 1.0,
		["name"] = "Starving Winter Wolf",
		["family"] = "Wolf",
		["min_level"] = 8,
		["max_level"] = 9,
		["area"] = "Dun Morogh",
	},
	[2000] = {
		["attack_speed"] = 1.0,
		["name"] = "Webwood Silkspinner",
		["family"] = "Spider",
		["min_level"] = 8,
		["max_level"] = 9,
		["area"] = "Teldrassil",
	},
	[118] = {
		["attack_speed"] = 1.0,
		["name"] = "Prowler",
		["family"] = "Wolf",
		["min_level"] = 9,
		["max_level"] = 10,
		["area"] = "Elwynn Forest",
	},
	[17199] = {
		["attack_speed"] = 1.0,
		["name"] = "Ravager Specimen",
		["family"] = "Ravager",
		["min_level"] = 9,
		["max_level"] = 10,
		["area"] = "Azuremyst Isle",
	},
	[1555] = {
		["attack_speed"] = 1.0,
		["name"] = "Vicious Night Web Spider",
		["family"] = "Spider",
		["min_level"] = 9,
		["max_level"] = 10,
		["area"] = "Tirisfal Glades",
	},
	[2960] = {
		["attack_speed"] = 1.0,
		["name"] = "Prairie Wolf Alpha",
		["family"] = "Wolf",
		["min_level"] = 9,
		["max_level"] = 10,
		["area"] = "Mulgore",
	},
	[1195] = {
		["attack_speed"] = 1.0,
		["name"] = "Forest Lurker",
		["family"] = "Spider",
		["min_level"] = 10,
		["max_level"] = 11,
		["area"] = "Loch Modan",
	},
	[1765] = {
		["attack_speed"] = 1.0,
		["name"] = "Worg",
		["family"] = "Wolf",
		["min_level"] = 10,
		["max_level"] = 11,
		["area"] = "Silverpine Forest",
	},
	[1132] = {
		["attack_speed"] = 1.0,
		["name"] = "Timber",
		["family"] = "Wolf",
		["min_level"] = 10,
		["max_level"] = 10,
		["area"] = "Dun Morogh",
	},
	[834] = {
		["attack_speed"] = 1.0,
		["name"] = "Coyote",
		["family"] = "Wolf",
		["min_level"] = 10,
		["max_level"] = 11,
		["area"] = "Westfall",
	},
	[2001] = {
		["attack_speed"] = 1.0,
		["name"] = "Giant Webwood Spider",
		["family"] = "Spider",
		["min_level"] = 10,
		["max_level"] = 11,
		["area"] = "Teldrassil",
	},
	[833] = {
		["attack_speed"] = 1.0,
		["name"] = "Coyote Packleader",
		["family"] = "Wolf",
		["min_level"] = 11,
		["max_level"] = 12,
		["area"] = "Westfall",
	},
	[7319] = {
		["attack_speed"] = 1.0,
		["name"] = "Lady Sathrah",
		["family"] = "Spider",
		["min_level"] = 12,
		["max_level"] = 12,
		["area"] = "Teldrassil",
	},
	[1693] = {
		["attack_speed"] = 1.0,
		["name"] = "Loch Crocolisk",
		["family"] = "Crocolisk",
		["min_level"] = 14,
		["max_level"] = 15,
		["area"] = "Loch Modan",
	},
	[442] = {
		["attack_speed"] = 1.0,
		["name"] = "Tarantula",
		["family"] = "Spider",
		["min_level"] = 15,
		["max_level"] = 16,
		["area"] = "Redridge Mountains",
	},
	[3461] = {
		["attack_speed"] = 1.0,
		["name"] = "Oasis Snapjaw",
		["family"] = "Turtle",
		["min_level"] = 15,
		["max_level"] = 16,
		["area"] = "The Barrens",
	},
	[4005] = {
		["attack_speed"] = 1.0,
		["name"] = "Deepmoss Creeper",
		["family"] = "Spider",
		["min_level"] = 16,
		["max_level"] = 17,
		["area"] = "Stonetalon Mountains",
	},
	[1923] = {
		["attack_speed"] = 1.0,
		["name"] = "Bloodsnout Worg",
		["family"] = "Wolf",
		["min_level"] = 16,
		["max_level"] = 17,
		["area"] = "Silverpine Forest",
	},
	[16349] = {
		["attack_speed"] = 1.0,
		["name"] = "Ghostclaw Ravager",
		["family"] = "Cat",
		["min_level"] = 16,
		["max_level"] = 17,
		["area"] = "Ghostlands",
	},
	[1185] = {
		["attack_speed"] = 1.0,
		["name"] = "Wood Lurker",
		["family"] = "Spider",
		["min_level"] = 17,
		["max_level"] = 18,
		["area"] = "Loch Modan",
	},
	[14266] = {
		["attack_speed"] = 1.0,
		["name"] = "Shanda the Spinner",
		["family"] = "Spider",
		["min_level"] = 19,
		["max_level"] = 19,
		["area"] = "Loch Modan",
	},
	[4006] = {
		["attack_speed"] = 1.0,
		["name"] = "Deepmoss Webspinner",
		["family"] = "Spider",
		["min_level"] = 19,
		["max_level"] = 20,
		["area"] = "Stonetalon Mountains",
	},
	[505] = {
		["attack_speed"] = 1.0,
		["name"] = "Greater Tarantula",
		["family"] = "Spider",
		["min_level"] = 19,
		["max_level"] = 20,
		["area"] = "Redridge Mountains",
	},
	[3823] = {
		["attack_speed"] = 1.0,
		["name"] = "Ghostpaw Runner",
		["family"] = "Wolf",
		["min_level"] = 19,
		["max_level"] = 20,
		["area"] = "Ashenvale",
	},
	[11921] = {
		["attack_speed"] = 1.0,
		["name"] = "Besseleth",
		["family"] = "Spider",
		["min_level"] = 21,
		["max_level"] = 21,
		["area"] = "Stonetalon Mountains",
	},
	[569] = {
		["attack_speed"] = 1.0,
		["name"] = "Green Recluse",
		["family"] = "Spider",
		["min_level"] = 21,
		["max_level"] = 22,
		["area"] = "Duskwood",
	},
	[2476] = {
		["attack_speed"] = 1.0,
		["name"] = "Large Loch Crocolisk",
		["family"] = "Crocolisk",
		["min_level"] = 22,
		["max_level"] = 22,
		["area"] = "Loch Modan",
	},
	[616] = {
		["attack_speed"] = 1.0,
		["name"] = "Chatter",
		["family"] = "Spider",
		["min_level"] = 23,
		["max_level"] = 23,
		["area"] = "Redridge Mountains",
	},
	[521] = {
		["attack_speed"] = 1.0,
		["name"] = "Lupos",
		["family"] = "Wolf",
		["min_level"] = 23,
		["max_level"] = 23,
		["area"] = "Duskwood",
	},
	[14279] = {
		["attack_speed"] = 1.0,
		["name"] = "Creepthess",
		["family"] = "Spider",
		["min_level"] = 24,
		["max_level"] = 24,
		["area"] = "Hillsbrad Foothills",
	},
	[1112] = {
		["attack_speed"] = 1.0,
		["name"] = "Leech Widow",
		["family"] = "Spider",
		["min_level"] = 24,
		["max_level"] = 24,
		["area"] = "Wetlands",
	},
	[2349] = {
		["attack_speed"] = 1.0,
		["name"] = "Giant Moss Creeper",
		["family"] = "Spider",
		["min_level"] = 24,
		["max_level"] = 25,
		["area"] = "Hillsbrad Foothills",
	},
	[628] = {
		["attack_speed"] = 1.0,
		["name"] = "Black Ravager",
		["family"] = "Wolf",
		["min_level"] = 24,
		["max_level"] = 25,
		["area"] = "Duskwood",
	},
	[2089] = {
		["attack_speed"] = 1.0,
		["name"] = "Giant Wetlands Crocolisk",
		["family"] = "Crocolisk",
		["min_level"] = 25,
		["max_level"] = 26,
		["area"] = "Wetlands",
	},
	[1258] = {
		["attack_speed"] = 1.0,
		["name"] = "Black Ravager Mastiff",
		["family"] = "Wolf",
		["min_level"] = 25,
		["max_level"] = 26,
		["area"] = "Duskwood",
	},
	[2348] = {
		["attack_speed"] = 1.0,
		["name"] = "Elder Moss Creeper",
		["family"] = "Spider",
		["min_level"] = 26,
		["max_level"] = 27,
		["area"] = "Hillsbrad Foothills",
	},
	[574] = {
		["attack_speed"] = 1.0,
		["name"] = "Naraxis",
		["family"] = "Spider",
		["min_level"] = 27,
		["max_level"] = 27,
		["area"] = "Duskwood",
	},
	[3825] = {
		["attack_speed"] = 1.0,
		["name"] = "Ghostpaw Alpha",
		["family"] = "Wolf",
		["min_level"] = 27,
		["max_level"] = 28,
		["area"] = "Ashenvale",
	},
	[3821] = {
		["attack_speed"] = 1.0,
		["name"] = "Wildthorn Lurker",
		["family"] = "Spider",
		["min_level"] = 28,
		["max_level"] = 29,
		["area"] = "Ashenvale",
	},
	[14223] = {
		["attack_speed"] = 1.0,
		["name"] = "Cranky Benj",
		["family"] = "Turtle",
		["min_level"] = 32,
		["max_level"] = 32,
		["area"] = "Alterac Mountains",
	},
	[2563] = {
		["attack_speed"] = 1.0,
		["name"] = "Plains Creeper",
		["family"] = "Spider",
		["min_level"] = 32,
		["max_level"] = 33,
		["area"] = "Arathi Highlands",
	},
	[4143] = {
		["attack_speed"] = 1.0,
		["name"] = "Sparkleshell Snapper",
		["family"] = "Turtle",
		["min_level"] = 34,
		["max_level"] = 35,
		["area"] = "Thousand Needles",
	},
	[2565] = {
		["attack_speed"] = 1.0,
		["name"] = "Giant Plains Creeper",
		["family"] = "Spider",
		["min_level"] = 35,
		["max_level"] = 36,
		["area"] = "Arathi Highlands",
	},
	[2727] = {
		["attack_speed"] = 1.0,
		["name"] = "Crag Coyote",
		["family"] = "Wolf",
		["min_level"] = 35,
		["max_level"] = 36,
		["area"] = "Badlands",
	},
	[4341] = {
		["attack_speed"] = 1.0,
		["name"] = "Drywallow Crocolisk",
		["family"] = "Crocolisk",
		["min_level"] = 35,
		["max_level"] = 36,
		["area"] = "Dustwallow Marsh",
	},
	[4343] = {
		["attack_speed"] = 1.0,
		["name"] = "Drywallow Snapper",
		["family"] = "Crocolisk",
		["min_level"] = 37,
		["max_level"] = 38,
		["area"] = "Dustwallow Marsh",
	},
	[4412] = {
		["attack_speed"] = 1.0,
		["name"] = "Darkfang Creeper",
		["family"] = "Spider",
		["min_level"] = 37,
		["max_level"] = 38,
		["area"] = "Dustwallow Marsh",
	},
	[2753] = {
		["attack_speed"] = 1.0,
		["name"] = "Barnabus",
		["family"] = "Wolf",
		["min_level"] = 38,
		["max_level"] = 38,
		["area"] = "Badlands",
	},
	[4344] = {
		["attack_speed"] = 1.0,
		["name"] = "Mottled Drywallow Crocolisk",
		["family"] = "Crocolisk",
		["min_level"] = 38,
		["max_level"] = 39,
		["area"] = "Dustwallow Marsh",
	},
	[14233] = {
		["attack_speed"] = 1.0,
		["name"] = "Ripscale",
		["family"] = "Crocolisk",
		["min_level"] = 37,
		["max_level"] = 37,
		["area"] = "Dustwallow Marsh",
	},
	[4345] = {
		["attack_speed"] = 1.0,
		["name"] = "Drywallow Daggermaw",
		["family"] = "Crocolisk",
		["min_level"] = 39,
		["max_level"] = 40,
		["area"] = "Dustwallow Marsh",
	},
	[769] = {
		["attack_speed"] = 1.0,
		["name"] = "Deathstrike Tarantula",
		["family"] = "Spider",
		["min_level"] = 40,
		["max_level"] = 41,
		["area"] = "Swamp of Sorrows",
	},
	[5286] = {
		["attack_speed"] = 1.0,
		["name"] = "Longtooth Runner",
		["family"] = "Wolf",
		["min_level"] = 40,
		["max_level"] = 41,
		["area"] = "Feralas",
	},
	[1087] = {
		["attack_speed"] = 1.0,
		["name"] = "Sawtooth Snapper",
		["family"] = "Crocolisk",
		["min_level"] = 41,
		["max_level"] = 42,
		["area"] = "Swamp of Sorrows",
	},
	[4841] = {
		["attack_speed"] = 1.0,
		["name"] = "Deadmire",
		["family"] = "Crocolisk",
		["min_level"] = 41,
		["max_level"] = 41,
		["area"] = "Dustwallow Marsh",
	},
	[8211] = {
		["attack_speed"] = 1.0,
		["name"] = "Old Cliff Jumper",
		["family"] = "Wolf",
		["min_level"] = 42,
		["max_level"] = 42,
		["area"] = "The Hinterlands",
	},
	[5356] = {
		["attack_speed"] = 1.0,
		["name"] = "Snarler",
		["family"] = "Wolf",
		["min_level"] = 42,
		["max_level"] = 42,
		["area"] = "Feralas",
	},
	[8959] = {
		["attack_speed"] = 1.0,
		["name"] = "Felpaw Wolf",
		["family"] = "Wolf",
		["min_level"] = 47,
		["max_level"] = 48,
		["area"] = "Felwood",
	},
	[8762] = {
		["attack_speed"] = 1.0,
		["name"] = "Timberweb Recluse",
		["family"] = "Spider",
		["min_level"] = 47,
		["max_level"] = 48,
		["area"] = "Azshara",
	},
	[14339] = {
		["attack_speed"] = 1.0,
		["name"] = "Death Howl",
		["family"] = "Wolf",
		["min_level"] = 49,
		["max_level"] = 49,
		["area"] = "Felwood",
	},
	[8277] = {
		["attack_speed"] = 1.0,
		["name"] = "Rekk'tilac",
		["family"] = "Spider",
		["min_level"] = 48,
		["max_level"] = 48,
		["area"] = "Searing Gorge",
	},
	[2505] = {
		["attack_speed"] = 1.0,
		["name"] = "Saltwater Snapjaw",
		["family"] = "Turtle",
		["min_level"] = 49,
		["max_level"] = 50,
		["area"] = "The Hinterlands",
	},
	[2681] = {
		["attack_speed"] = 1.0,
		["name"] = "Vilebranch Raiding Wolf",
		["family"] = "Wolf",
		["min_level"] = 50,
		["max_level"] = 51,
		["area"] = "The Hinterlands",
	},
	[3581] = {
		["attack_speed"] = 1.0,
		["name"] = "Sewer Beast",
		["family"] = "Crocolisk",
		["min_level"] = 50,
		["max_level"] = 50,
		["area"] = "Stormwind City",
	},
	[8961] = {
		["attack_speed"] = 1.0,
		["name"] = "Felpaw Ravager",
		["family"] = "Wolf",
		["min_level"] = 51,
		["max_level"] = 52,
		["area"] = "Felwood",
	},
	[8213] = {
		["attack_speed"] = 1.0,
		["name"] = "Ironback",
		["family"] = "Turtle",
		["min_level"] = 51,
		["max_level"] = 51,
		["area"] = "The Hinterlands",
	},
	[6585] = {
		["attack_speed"] = 1.0,
		["name"] = "Uhk'loc",
		["family"] = "Gorilla",
		["min_level"] = 52,
		["max_level"] = 53,
		["area"] = "Un'Goro Crater",
	},
	[1817] = {
		["attack_speed"] = 1.0,
		["name"] = "Diseased Wolf",
		["family"] = "Wolf",
		["min_level"] = 53,
		["max_level"] = 54,
		["area"] = "Western Plaguelands",
	},
	[1824] = {
		["attack_speed"] = 1.0,
		["name"] = "Plague Lurker",
		["family"] = "Spider",
		["min_level"] = 54,
		["max_level"] = 55,
		["area"] = "Western Plaguelands",
	},
	[16934] = {
		["attack_speed"] = 1.0,
		["name"] = "Quillfang Ravager",
		["family"] = "Ravager",
		["min_level"] = 62,
		["max_level"] = 63,
		["area"] = "Hellfire Peninsula",
	},
	[19350] = {
		["attack_speed"] = 1.0,
		["name"] = "Thornfang Venomspitter",
		["family"] = "Ravager",
		["min_level"] = 62,
		["max_level"] = 63,
		["area"] = "Hellfire Peninsula",
	},
	[18466] = {
		["attack_speed"] = 1.0,
		["name"] = "Dreadfang Lurker",
		["family"] = "Spider",
		["min_level"] = 63,
		["max_level"] = 64,
		["area"] = "Terokkar Forest",
	},
	[18467] = {
		["attack_speed"] = 1.0,
		["name"] = "Dreadfang Widow",
		["family"] = "Spider",
		["min_level"] = 64,
		["max_level"] = 65,
		["area"] = "Terokkar Forest",
	},
	[21956] = {
		["attack_speed"] = 1.0,
		["name"] = "Rema",
		["family"] = "Wolf",
		["min_level"] = 66,
		["max_level"] = 66,
		["area"] = "Blade's Edge Mountains",
	},
	[20634] = {
		["attack_speed"] = 1.0,
		["name"] = "Scythetooth Raptor",
		["family"] = "Raptor",
		["min_level"] = 68,
		["max_level"] = 69,
		["area"] = "Netherstorm",
	},
	[3098] = {
		["attack_speed"] = 1.0,
		["name"] = "Mottled Boar",
		["family"] = "Boar",
		["min_level"] = 1,
		["max_level"] = 2,
		["area"] = "Durotar",
	},
	[1984] = {
		["attack_speed"] = 1.0,
		["name"] = "Young Thistle Boar",
		["family"] = "Boar",
		["min_level"] = 1,
		["max_level"] = 2,
		["area"] = "Teldrassil",
	},
	[1985] = {
		["attack_speed"] = 1.0,
		["name"] = "Thistle Boar",
		["family"] = "Boar",
		["min_level"] = 2,
		["max_level"] = 3,
		["area"] = "Teldrassil",
	},
	[708] = {
		["attack_speed"] = 1.0,
		["name"] = "Small Crag Boar",
		["family"] = "Boar",
		["min_level"] = 3,
		["max_level"] = 3,
		["area"] = "Dun Morogh",
	},
	[2966] = {
		["attack_speed"] = 1.0,
		["name"] = "Battleboar",
		["family"] = "Boar",
		["min_level"] = 3,
		["max_level"] = 4,
		["area"] = "Mulgore",
	},
	[2954] = {
		["attack_speed"] = 1.0,
		["name"] = "Bristleback Battleboar",
		["family"] = "Boar",
		["min_level"] = 4,
		["max_level"] = 5,
		["area"] = "Mulgore",
	},
	[1125] = {
		["attack_speed"] = 1.0,
		["name"] = "Crag Boar",
		["family"] = "Boar",
		["min_level"] = 5,
		["max_level"] = 6,
		["area"] = "Dun Morogh",
	},
	[3099] = {
		["attack_speed"] = 1.0,
		["name"] = "Dire Mottled Boar",
		["family"] = "Boar",
		["min_level"] = 6,
		["max_level"] = 7,
		["area"] = "Durotar",
	},
	[1126] = {
		["attack_speed"] = 1.0,
		["name"] = "Large Crag Boar",
		["family"] = "Boar",
		["min_level"] = 6,
		["max_level"] = 7,
		["area"] = "Dun Morogh",
	},
	[390] = {
		["attack_speed"] = 1.0,
		["name"] = "Porcine Entourage",
		["family"] = "Boar",
		["min_level"] = 7,
		["max_level"] = 7,
		["area"] = "Elwynn Forest",
	},
	[1127] = {
		["attack_speed"] = 1.0,
		["name"] = "Elder Crag Boar",
		["family"] = "Boar",
		["min_level"] = 7,
		["max_level"] = 8,
		["area"] = "Dun Morogh",
	},
	[524] = {
		["attack_speed"] = 1.0,
		["name"] = "Rockhide Boar",
		["family"] = "Boar",
		["min_level"] = 7,
		["max_level"] = 8,
		["area"] = "Elwynn Forest",
	},
	[113] = {
		["attack_speed"] = 1.0,
		["name"] = "Stonetusk Boar",
		["family"] = "Boar",
		["min_level"] = 7,
		["max_level"] = 8,
		["area"] = "Elwynn Forest",
	},
	[3100] = {
		["attack_speed"] = 1.0,
		["name"] = "Elder Mottled Boar",
		["family"] = "Boar",
		["min_level"] = 8,
		["max_level"] = 9,
		["area"] = "Durotar",
	},
	[1689] = {
		["attack_speed"] = 1.0,
		["name"] = "Scarred Crag Boar",
		["family"] = "Boar",
		["min_level"] = 9,
		["max_level"] = 10,
		["area"] = "Dun Morogh",
	},
	[330] = {
		["attack_speed"] = 1.0,
		["name"] = "Princess",
		["family"] = "Boar",
		["min_level"] = 9,
		["max_level"] = 9,
		["area"] = "Elwynn Forest",
	},
	[1190] = {
		["attack_speed"] = 1.0,
		["name"] = "Mountain Boar",
		["family"] = "Boar",
		["min_level"] = 10,
		["max_level"] = 11,
		["area"] = "Loch Modan",
	},
	[3225] = {
		["attack_speed"] = 1.0,
		["name"] = "Corrupted Mottled Boar",
		["family"] = "Boar",
		["min_level"] = 10,
		["max_level"] = 11,
		["area"] = "Durotar",
	},
	[119] = {
		["attack_speed"] = 1.0,
		["name"] = "Longsnout",
		["family"] = "Boar",
		["min_level"] = 10,
		["max_level"] = 11,
		["area"] = "Elwynn Forest",
	},
	[454] = {
		["attack_speed"] = 1.0,
		["name"] = "Young Goretusk",
		["family"] = "Boar",
		["min_level"] = 12,
		["max_level"] = 13,
		["area"] = "Westfall",
	},
	[1191] = {
		["attack_speed"] = 1.0,
		["name"] = "Mangy Mountain Boar",
		["family"] = "Boar",
		["min_level"] = 14,
		["max_level"] = 15,
		["area"] = "Loch Modan",
	},
	[157] = {
		["attack_speed"] = 1.0,
		["name"] = "Goretusk",
		["family"] = "Boar",
		["min_level"] = 14,
		["max_level"] = 15,
		["area"] = "Westfall",
	},
	[1192] = {
		["attack_speed"] = 1.0,
		["name"] = "Elder Mountain Boar",
		["family"] = "Boar",
		["min_level"] = 16,
		["max_level"] = 17,
		["area"] = "Loch Modan",
	},
	[345] = {
		["attack_speed"] = 1.0,
		["name"] = "Bellygrub",
		["family"] = "Boar",
		["min_level"] = 24,
		["max_level"] = 24,
		["area"] = "Redridge Mountains",
	},
	[5992] = {
		["attack_speed"] = 1.0,
		["name"] = "Ashmane Boar",
		["family"] = "Boar",
		["min_level"] = 48,
		["max_level"] = 49,
		["area"] = "Blasted Lands",
	},
	[8303] = {
		["attack_speed"] = 1.0,
		["name"] = "Grunter",
		["family"] = "Boar",
		["min_level"] = 50,
		["max_level"] = 50,
		["area"] = "Blasted Lands",
	},
	[16117] = {
		["attack_speed"] = 1.0,
		["name"] = "Plagued Swine",
		["family"] = "Boar",
		["min_level"] = 60,
		["max_level"] = 60,
		["area"] = "Eastern Plaguelands",
	},
	[3124] = {
		["attack_speed"] = 1.0,
		["name"] = "Scorpid Worker",
		["family"] = "Scorpid",
		["min_level"] = 3,
		["max_level"] = 3,
		["area"] = "Durotar",
	},
	[3281] = {
		["attack_speed"] = 1.0,
		["name"] = "Sarkoth",
		["family"] = "Scorpid",
		["min_level"] = 4,
		["max_level"] = 4,
		["area"] = "Durotar",
	},
	[1995] = {
		["attack_speed"] = 1.0,
		["name"] = "Strigid Owl",
		["family"] = "Owl",
		["min_level"] = 5,
		["max_level"] = 6,
		["area"] = "Teldrassil",
	},
	[3106] = {
		["attack_speed"] = 1.0,
		["name"] = "Pygmy Surf Crawler",
		["family"] = "Crab",
		["min_level"] = 5,
		["max_level"] = 6,
		["area"] = "Durotar",
	},
	[1196] = {
		["attack_speed"] = 1.0,
		["name"] = "Ice Claw Bear",
		["family"] = "Bear",
		["min_level"] = 7,
		["max_level"] = 8,
		["area"] = "Dun Morogh",
	},
	[15652] = {
		["attack_speed"] = 1.0,
		["name"] = "Elder Springpaw",
		["family"] = "Cat",
		["min_level"] = 8,
		["max_level"] = 9,
		["area"] = "Eversong Woods",
	},
	[822] = {
		["attack_speed"] = 1.0,
		["name"] = "Young Forest Bear",
		["family"] = "Bear",
		["min_level"] = 8,
		["max_level"] = 9,
		["area"] = "Elwynn Forest",
	},
	[1997] = {
		["attack_speed"] = 1.0,
		["name"] = "Strigid Hunter",
		["family"] = "Owl",
		["min_level"] = 8,
		["max_level"] = 9,
		["area"] = "Teldrassil",
	},
	[3127] = {
		["attack_speed"] = 1.0,
		["name"] = "Venomtail Scorpid",
		["family"] = "Scorpid",
		["min_level"] = 9,
		["max_level"] = 10,
		["area"] = "Durotar",
	},
	[3108] = {
		["attack_speed"] = 1.0,
		["name"] = "Encrusted Surf Crawler",
		["family"] = "Crab",
		["min_level"] = 9,
		["max_level"] = 10,
		["area"] = "Durotar",
	},
	[2163] = {
		["attack_speed"] = 1.0,
		["name"] = "Thistle Bear",
		["family"] = "Bear",
		["min_level"] = 11,
		["max_level"] = 12,
		["area"] = "Darkshore",
	},
	[5823] = {
		["attack_speed"] = 1.0,
		["name"] = "Death Flayer",
		["family"] = "Scorpid",
		["min_level"] = 11,
		["max_level"] = 11,
		["area"] = "Durotar",
	},
	[1778] = {
		["attack_speed"] = 1.0,
		["name"] = "Ferocious Grizzled Bear",
		["family"] = "Bear",
		["min_level"] = 11,
		["max_level"] = 12,
		["area"] = "Silverpine Forest",
	},
	[1961] = {
		["attack_speed"] = 1.0,
		["name"] = "Mangeclaw",
		["family"] = "Bear",
		["min_level"] = 11,
		["max_level"] = 11,
		["area"] = "Dun Morogh",
	},
	[2232] = {
		["attack_speed"] = 1.0,
		["name"] = "Tide Crawler",
		["family"] = "Crab",
		["min_level"] = 12,
		["max_level"] = 14,
		["area"] = "Darkshore",
	},
	[1130] = {
		["attack_speed"] = 1.0,
		["name"] = "Bjarn",
		["family"] = "Bear",
		["min_level"] = 12,
		["max_level"] = 12,
		["area"] = "Dun Morogh",
	},
	[16348] = {
		["attack_speed"] = 1.0,
		["name"] = "Ghostclaw Lynx",
		["family"] = "Cat",
		["min_level"] = 13,
		["max_level"] = 14,
		["area"] = "Ghostlands",
	},
	[1189] = {
		["attack_speed"] = 1.0,
		["name"] = "Black Bear Patriarch",
		["family"] = "Bear",
		["min_level"] = 16,
		["max_level"] = 17,
		["area"] = "Loch Modan",
	},
	[1216] = {
		["attack_speed"] = 1.0,
		["name"] = "Shore Crawler",
		["family"] = "Crab",
		["min_level"] = 17,
		["max_level"] = 18,
		["area"] = "Westfall",
	},
	[6788] = {
		["attack_speed"] = 1.0,
		["name"] = "Den Mother",
		["family"] = "Bear",
		["min_level"] = 18,
		["max_level"] = 19,
		["area"] = "Darkshore",
	},
	[3619] = {
		["attack_speed"] = 1.0,
		["name"] = "Ghost Saber",
		["family"] = "Cat",
		["min_level"] = 19,
		["max_level"] = 20,
		["area"] = "Darkshore",
	},
	[3812] = {
		["attack_speed"] = 1.0,
		["name"] = "Clattering Crawler",
		["family"] = "Crab",
		["min_level"] = 19,
		["max_level"] = 20,
		["area"] = "Ashenvale",
	},
	[1225] = {
		["attack_speed"] = 1.0,
		["name"] = "Ol' Sooty",
		["family"] = "Bear",
		["min_level"] = 20,
		["max_level"] = 20,
		["area"] = "Loch Modan",
	},
	[3809] = {
		["attack_speed"] = 1.0,
		["name"] = "Ashenvale Bear",
		["family"] = "Bear",
		["min_level"] = 21,
		["max_level"] = 22,
		["area"] = "Ashenvale",
	},
	[2351] = {
		["attack_speed"] = 1.0,
		["name"] = "Gray Bear",
		["family"] = "Bear",
		["min_level"] = 21,
		["max_level"] = 22,
		["area"] = "Hillsbrad Foothills",
	},
	[3810] = {
		["attack_speed"] = 1.0,
		["name"] = "Elder Ashenvale Bear",
		["family"] = "Bear",
		["min_level"] = 25,
		["max_level"] = 26,
		["area"] = "Ashenvale",
	},
	[4696] = {
		["attack_speed"] = 1.0,
		["name"] = "Scorpashi Snapper",
		["family"] = "Scorpid",
		["min_level"] = 30,
		["max_level"] = 31,
		["area"] = "Desolace",
	},
	[4140] = {
		["attack_speed"] = 1.0,
		["name"] = "Scorpid Reaver",
		["family"] = "Scorpid",
		["min_level"] = 31,
		["max_level"] = 32,
		["area"] = "Thousand Needles",
	},
	[4697] = {
		["attack_speed"] = 1.0,
		["name"] = "Scorpashi Lasher",
		["family"] = "Scorpid",
		["min_level"] = 34,
		["max_level"] = 35,
		["area"] = "Desolace",
	},
	[5937] = {
		["attack_speed"] = 1.0,
		["name"] = "Vile Sting",
		["family"] = "Scorpid",
		["min_level"] = 35,
		["max_level"] = 35,
		["area"] = "Thousand Needles",
	},
	[922] = {
		["attack_speed"] = 1.0,
		["name"] = "Silt Crawler",
		["family"] = "Crab",
		["min_level"] = 40,
		["max_level"] = 41,
		["area"] = "Swamp of Sorrows",
	},
	[5422] = {
		["attack_speed"] = 1.0,
		["name"] = "Scorpid Hunter",
		["family"] = "Scorpid",
		["min_level"] = 40,
		["max_level"] = 41,
		["area"] = "Tanaris",
	},
	[5268] = {
		["attack_speed"] = 1.0,
		["name"] = "Ironfur Bear",
		["family"] = "Bear",
		["min_level"] = 41,
		["max_level"] = 42,
		["area"] = "Feralas",
	},
	[1088] = {
		["attack_speed"] = 1.0,
		["name"] = "Monstrous Crawler",
		["family"] = "Crab",
		["min_level"] = 43,
		["max_level"] = 44,
		["area"] = "Swamp of Sorrows",
	},
	[731] = {
		["attack_speed"] = 1.0,
		["name"] = "King Bangalash",
		["family"] = "Cat",
		["min_level"] = 43,
		["max_level"] = 43,
		["area"] = "Stranglethorn Vale",
	},
	[5352] = {
		["attack_speed"] = 1.0,
		["name"] = "Old Grizzlegut",
		["family"] = "Bear",
		["min_level"] = 43,
		["max_level"] = 43,
		["area"] = "Feralas",
	},
	[5274] = {
		["attack_speed"] = 1.0,
		["name"] = "Ironfur Patriarch",
		["family"] = "Bear",
		["min_level"] = 48,
		["max_level"] = 49,
		["area"] = "Feralas",
	},
	[8958] = {
		["attack_speed"] = 1.0,
		["name"] = "Angerclaw Mauler",
		["family"] = "Bear",
		["min_level"] = 49,
		["max_level"] = 50,
		["area"] = "Felwood",
	},
	[14344] = {
		["attack_speed"] = 1.0,
		["name"] = "Mongress",
		["family"] = "Bear",
		["min_level"] = 50,
		["max_level"] = 50,
		["area"] = "Felwood",
	},
	[7099] = {
		["attack_speed"] = 1.0,
		["name"] = "Ironbeak Hunter",
		["family"] = "Owl",
		["min_level"] = 50,
		["max_level"] = 51,
		["area"] = "Felwood",
	},
	[14343] = {
		["attack_speed"] = 1.0,
		["name"] = "Olm the Wise",
		["family"] = "Owl",
		["min_level"] = 52,
		["max_level"] = 52,
		["area"] = "Felwood",
	},
	[8301] = {
		["attack_speed"] = 1.0,
		["name"] = "Clack the Reaver",
		["family"] = "Scorpid",
		["min_level"] = 53,
		["max_level"] = 53,
		["area"] = "Blasted Lands",
	},
	[7444] = {
		["attack_speed"] = 1.0,
		["name"] = "Shardtooth Bear",
		["family"] = "Bear",
		["min_level"] = 53,
		["max_level"] = 54,
		["area"] = "Winterspring",
	},
	[7455] = {
		["attack_speed"] = 1.0,
		["name"] = "Winterspring Owl",
		["family"] = "Owl",
		["min_level"] = 54,
		["max_level"] = 56,
		["area"] = "Winterspring",
	},
	[9695] = {
		["attack_speed"] = 1.0,
		["name"] = "Deathlash Scorpid",
		["family"] = "Scorpid",
		["min_level"] = 54,
		["max_level"] = 55,
		["area"] = "Burning Steppes",
	},
	[1816] = {
		["attack_speed"] = 1.0,
		["name"] = "Diseased Grizzly",
		["family"] = "Bear",
		["min_level"] = 55,
		["max_level"] = 56,
		["area"] = "Western Plaguelands",
	},
	[7456] = {
		["attack_speed"] = 1.0,
		["name"] = "Winterspring Screecher",
		["family"] = "Owl",
		["min_level"] = 57,
		["max_level"] = 59,
		["area"] = "Winterspring",
	},
	[7445] = {
		["attack_speed"] = 1.0,
		["name"] = "Elder Shardtooth",
		["family"] = "Bear",
		["min_level"] = 57,
		["max_level"] = 58,
		["area"] = "Winterspring",
	},
	[17039] = {
		["attack_speed"] = 1.0,
		["name"] = "Male Kaliri Hatchling",
		["family"] = "Owl",
		["min_level"] = 61,
		["max_level"] = 61,
		["area"] = "Hellfire Peninsula",
	},
	[17034] = {
		["attack_speed"] = 1.0,
		["name"] = "Female Kaliri Hatchling",
		["family"] = "Owl",
		["min_level"] = 62,
		["max_level"] = 62,
		["area"] = "Hellfire Peninsula",
	},
	[22100] = {
		["attack_speed"] = 1.0,
		["name"] = "Scorpid Bonecrawler",
		["family"] = "Scorpid",
		["min_level"] = 64,
		["max_level"] = 65,
		["area"] = "Terokkar Forest",
	},
	[18220] = {
		["attack_speed"] = 1.0,
		["name"] = "Ravenous Windroc",
		["family"] = "Owl",
		["min_level"] = 65,
		["max_level"] = 66,
		["area"] = "Nagrand",
	},
	[22265] = {
		["attack_speed"] = 1.0,
		["name"] = "Shadowwing Owl",
		["family"] = "Owl",
		["min_level"] = 66,
		["max_level"] = 67,
		["area"] = "Shadowmoon Valley",
	},
	[17129] = {
		["attack_speed"] = 1.0,
		["name"] = "Greater Windroc",
		["family"] = "Owl",
		["min_level"] = 66,
		["max_level"] = 67,
		["area"] = "Nagrand",
	},
	[18257] = {
		["attack_speed"] = 1.0,
		["name"] = "Gutripper",
		["family"] = "Owl",
		["min_level"] = 67,
		["max_level"] = 67,
		["area"] = "Nagrand",
	},
	[20671] = {
		["attack_speed"] = 1.0,
		["name"] = "Ripfang Lynx",
		["family"] = "Cat",
		["min_level"] = 68,
		["max_level"] = 69,
		["area"] = "Netherstorm",
	},
	[2042] = {
		["attack_speed"] = 1.0,
		["name"] = "Nightsaber",
		["family"] = "Cat",
		["min_level"] = 5,
		["max_level"] = 6,
		["area"] = "Teldrassil",
	},
	[1199] = {
		["attack_speed"] = 1.0,
		["name"] = "Juvenile Snow Leopard",
		["family"] = "Cat",
		["min_level"] = 5,
		["max_level"] = 6,
		["area"] = "Dun Morogh",
	},
	[1553] = {
		["attack_speed"] = 1.0,
		["name"] = "Greater Duskbat",
		["family"] = "Bat",
		["min_level"] = 6,
		["max_level"] = 7,
		["area"] = "Tirisfal Glades",
	},
	[3121] = {
		["attack_speed"] = 1.0,
		["name"] = "Durotar Tiger",
		["family"] = "Cat",
		["min_level"] = 7,
		["max_level"] = 8,
		["area"] = "Durotar",
	},
	[3035] = {
		["attack_speed"] = 1.0,
		["name"] = "Flatland Cougar",
		["family"] = "Cat",
		["min_level"] = 7,
		["max_level"] = 8,
		["area"] = "Mulgore",
	},
	[2957] = {
		["attack_speed"] = 1.0,
		["name"] = "Elder Plainstrider",
		["family"] = "Tallstrider",
		["min_level"] = 8,
		["max_level"] = 9,
		["area"] = "Mulgore",
	},
	[3068] = {
		["attack_speed"] = 1.0,
		["name"] = "Mazzranache",
		["family"] = "Tallstrider",
		["min_level"] = 9,
		["max_level"] = 9,
		["area"] = "Mulgore",
	},
	[2070] = {
		["attack_speed"] = 1.0,
		["name"] = "Moonstalker Runt",
		["family"] = "Cat",
		["min_level"] = 10,
		["max_level"] = 11,
		["area"] = "Darkshore",
	},
	[2321] = {
		["attack_speed"] = 1.0,
		["name"] = "Foreststrider Fledgling",
		["family"] = "Tallstrider",
		["min_level"] = 11,
		["max_level"] = 13,
		["area"] = "Darkshore",
	},
	[3246] = {
		["attack_speed"] = 1.0,
		["name"] = "Fleeting Plainstrider",
		["family"] = "Tallstrider",
		["min_level"] = 12,
		["max_level"] = 13,
		["area"] = "The Barrens",
	},
	[3241] = {
		["attack_speed"] = 1.0,
		["name"] = "Savannah Patriarch",
		["family"] = "Cat",
		["min_level"] = 15,
		["max_level"] = 16,
		["area"] = "The Barrens",
	},
	[3245] = {
		["attack_speed"] = 1.0,
		["name"] = "Ornery Plainstrider",
		["family"] = "Tallstrider",
		["min_level"] = 16,
		["max_level"] = 17,
		["area"] = "The Barrens",
	},
	[2323] = {
		["attack_speed"] = 1.0,
		["name"] = "Giant Foreststrider",
		["family"] = "Tallstrider",
		["min_level"] = 17,
		["max_level"] = 19,
		["area"] = "Darkshore",
	},
	[2237] = {
		["attack_speed"] = 1.0,
		["name"] = "Moonstalker Sire",
		["family"] = "Cat",
		["min_level"] = 17,
		["max_level"] = 18,
		["area"] = "Darkshore",
	},
	[2384] = {
		["attack_speed"] = 1.0,
		["name"] = "Starving Mountain Lion",
		["family"] = "Cat",
		["min_level"] = 23,
		["max_level"] = 24,
		["area"] = "Hillsbrad Foothills",
	},
	[4067] = {
		["attack_speed"] = 1.0,
		["name"] = "Twilight Runner",
		["family"] = "Cat",
		["min_level"] = 23,
		["max_level"] = 24,
		["area"] = "Stonetalon Mountains",
	},
	[4126] = {
		["attack_speed"] = 1.0,
		["name"] = "Crag Stalker",
		["family"] = "Cat",
		["min_level"] = 25,
		["max_level"] = 26,
		["area"] = "Thousand Needles",
	},
	[681] = {
		["attack_speed"] = 1.0,
		["name"] = "Young Stranglethorn Tiger",
		["family"] = "Cat",
		["min_level"] = 30,
		["max_level"] = 31,
		["area"] = "Stranglethorn Vale",
	},
	[683] = {
		["attack_speed"] = 1.0,
		["name"] = "Young Panther",
		["family"] = "Cat",
		["min_level"] = 30,
		["max_level"] = 31,
		["area"] = "Stranglethorn Vale",
	},
	[736] = {
		["attack_speed"] = 1.0,
		["name"] = "Panther",
		["family"] = "Cat",
		["min_level"] = 32,
		["max_level"] = 33,
		["area"] = "Stranglethorn Vale",
	},
	[2731] = {
		["attack_speed"] = 1.0,
		["name"] = "Ridge Stalker",
		["family"] = "Cat",
		["min_level"] = 36,
		["max_level"] = 37,
		["area"] = "Badlands",
	},
	[2732] = {
		["attack_speed"] = 1.0,
		["name"] = "Ridge Huntress",
		["family"] = "Cat",
		["min_level"] = 38,
		["max_level"] = 39,
		["area"] = "Badlands",
	},
	[2522] = {
		["attack_speed"] = 1.0,
		["name"] = "Jaguero Stalker",
		["family"] = "Cat",
		["min_level"] = 41,
		["max_level"] = 41,
		["area"] = "Stranglethorn Vale",
	},
	[8600] = {
		["attack_speed"] = 1.0,
		["name"] = "Plaguebat",
		["family"] = "Bat",
		["min_level"] = 53,
		["max_level"] = 55,
		["area"] = "Eastern Plaguelands",
	},
	[8601] = {
		["attack_speed"] = 1.0,
		["name"] = "Noxious Plaguebat",
		["family"] = "Bat",
		["min_level"] = 54,
		["max_level"] = 56,
		["area"] = "Eastern Plaguelands",
	},
	[7430] = {
		["attack_speed"] = 1.0,
		["name"] = "Frostsaber Cub",
		["family"] = "Cat",
		["min_level"] = 55,
		["max_level"] = 56,
		["area"] = "Winterspring",
	},
	[8602] = {
		["attack_speed"] = 1.0,
		["name"] = "Monstrous Plaguebat",
		["family"] = "Bat",
		["min_level"] = 56,
		["max_level"] = 58,
		["area"] = "Eastern Plaguelands",
	},
	[21022] = {
		["attack_speed"] = 1.0,
		["name"] = "Grovestalker Lynx",
		["family"] = "Cat",
		["min_level"] = 65,
		["max_level"] = 66,
		["area"] = "Blade's Edge Mountains",
	},
	[22807] = {
		["attack_speed"] = 1.0,
		["name"] = "Lost Torranche",
		["family"] = "Tallstrider",
		["min_level"] = 70,
		["max_level"] = 70,
		["area"] = "Terokkar Forest",
	},
	[682] = {
		["attack_speed"] = 1.0,
		["name"] = "Stranglethorn Tiger",
		["family"] = "Cat",
		["min_level"] = 32,
		["max_level"] = 33,
		["area"] = "Stranglethorn Vale",
	},
	[976] = {
		["attack_speed"] = 1.0,
		["name"] = "Kurzen War Tiger",
		["family"] = "Cat",
		["min_level"] = 32,
		["max_level"] = 33,
		["area"] = "Stranglethorn Vale",
	},
	[4688] = {
		["attack_speed"] = 1.0,
		["name"] = "Bonepaw Hyena",
		["family"] = "Hyena",
		["min_level"] = 33,
		["max_level"] = 35,
		["area"] = "Desolace",
	},
	[4950] = {
		["attack_speed"] = 1.0,
		["name"] = "Spot",
		["family"] = "Wolf",
		["min_level"] = 35,
		["max_level"] = 35,
		["area"] = "Dustwallow Marsh",
	},
	[767] = {
		["attack_speed"] = 1.0,
		["name"] = "Swamp Jaguar",
		["family"] = "Cat",
		["min_level"] = 36,
		["max_level"] = 37,
		["area"] = "Swamp of Sorrows",
	},
	[4662] = {
		["attack_speed"] = 1.0,
		["name"] = "Magram Bonepaw",
		["family"] = "Hyena",
		["min_level"] = 37,
		["max_level"] = 38,
		["area"] = "Desolace",
	},
	[2728] = {
		["attack_speed"] = 1.0,
		["name"] = "Feral Crag Coyote",
		["family"] = "Wolf",
		["min_level"] = 37,
		["max_level"] = 38,
		["area"] = "Badlands",
	},
	[729] = {
		["attack_speed"] = 1.0,
		["name"] = "Sin'Dall",
		["family"] = "Cat",
		["min_level"] = 37,
		["max_level"] = 37,
		["area"] = "Stranglethorn Vale",
	},
	[2850] = {
		["attack_speed"] = 1.0,
		["name"] = "Broken Tooth",
		["family"] = "Cat",
		["min_level"] = 37,
		["max_level"] = 37,
		["area"] = "Badlands",
	},
	[2729] = {
		["attack_speed"] = 1.0,
		["name"] = "Elder Crag Coyote",
		["family"] = "Wolf",
		["min_level"] = 39,
		["max_level"] = 40,
		["area"] = "Badlands",
	},
	[728] = {
		["attack_speed"] = 1.0,
		["name"] = "Bhag'thera",
		["family"] = "Cat",
		["min_level"] = 40,
		["max_level"] = 40,
		["area"] = "Stranglethorn Vale",
	},
	[2734] = {
		["attack_speed"] = 1.0,
		["name"] = "Ridge Stalker Patriarch",
		["family"] = "Cat",
		["min_level"] = 40,
		["max_level"] = 41,
		["area"] = "Badlands",
	},
	[5425] = {
		["attack_speed"] = 1.0,
		["name"] = "Starving Blisterpaw",
		["family"] = "Hyena",
		["min_level"] = 41,
		["max_level"] = 42,
		["area"] = "Tanaris",
	},
	[2730] = {
		["attack_speed"] = 1.0,
		["name"] = "Rabid Crag Coyote",
		["family"] = "Wolf",
		["min_level"] = 42,
		["max_level"] = 43,
		["area"] = "Badlands",
	},
	[1713] = {
		["attack_speed"] = 1.0,
		["name"] = "Elder Shadowmaw Panther",
		["family"] = "Cat",
		["min_level"] = 42,
		["max_level"] = 43,
		["area"] = "Stranglethorn Vale",
	},
	[8208] = {
		["attack_speed"] = 1.0,
		["name"] = "Murderous Blisterpaw",
		["family"] = "Hyena",
		["min_level"] = 43,
		["max_level"] = 43,
		["area"] = "Tanaris",
	},
	[5426] = {
		["attack_speed"] = 1.0,
		["name"] = "Blisterpaw Hyena",
		["family"] = "Hyena",
		["min_level"] = 44,
		["max_level"] = 45,
		["area"] = "Tanaris",
	},
	[2926] = {
		["attack_speed"] = 1.0,
		["name"] = "Silvermane Stalker",
		["family"] = "Wolf",
		["min_level"] = 47,
		["max_level"] = 48,
		["area"] = "The Hinterlands",
	},
	[5427] = {
		["attack_speed"] = 1.0,
		["name"] = "Rabid Blisterpaw",
		["family"] = "Hyena",
		["min_level"] = 47,
		["max_level"] = 48,
		["area"] = "Tanaris",
	},
	[8300] = {
		["attack_speed"] = 1.0,
		["name"] = "Ravage",
		["family"] = "Hyena",
		["min_level"] = 51,
		["max_level"] = 51,
		["area"] = "Blasted Lands",
	},
	[7055] = {
		["attack_speed"] = 1.0,
		["name"] = "Blackrock Worg",
		["family"] = "Wolf",
		["min_level"] = 54,
		["max_level"] = 55,
		["area"] = "Burning Steppes",
	},
	[10200] = {
		["attack_speed"] = 1.0,
		["name"] = "Rak'Shiri",
		["family"] = "Cat",
		["min_level"] = 57,
		["max_level"] = 57,
		["area"] = "Winterspring",
	},
	[7433] = {
		["attack_speed"] = 1.0,
		["name"] = "Frostsaber Huntress",
		["family"] = "Cat",
		["min_level"] = 58,
		["max_level"] = 59,
		["area"] = "Winterspring",
	},
	[16932] = {
		["attack_speed"] = 1.0,
		["name"] = "Razorfang Hatchling",
		["family"] = "Ravager",
		["min_level"] = 59,
		["max_level"] = 60,
		["area"] = "Hellfire Peninsula",
	},
	[7432] = {
		["attack_speed"] = 1.0,
		["name"] = "Frostsaber Stalker",
		["family"] = "Cat",
		["min_level"] = 59,
		["max_level"] = 60,
		["area"] = "Winterspring",
	},
	[22123] = {
		["attack_speed"] = 1.0,
		["name"] = "Rip-Blade Ravager",
		["family"] = "Ravager",
		["min_level"] = 63,
		["max_level"] = 63,
		["area"] = "Blade's Edge Mountains",
	},
	[2578] = {
		["attack_speed"] = 1.0,
		["name"] = "Young Mesa Buzzard",
		["family"] = "Carrion Bird",
		["min_level"] = 31,
		["max_level"] = 32,
		["area"] = "Arathi Highlands",
	},
	[2579] = {
		["attack_speed"] = 1.0,
		["name"] = "Mesa Buzzard",
		["family"] = "Carrion Bird",
		["min_level"] = 34,
		["max_level"] = 35,
		["area"] = "Arathi Highlands",
	},
	[6013] = {
		["attack_speed"] = 1.0,
		["name"] = "Wayward Buzzard",
		["family"] = "Carrion Bird",
		["min_level"] = 35,
		["max_level"] = 37,
		["area"] = "Badlands",
	},
	[4346] = {
		["attack_speed"] = 1.0,
		["name"] = "Noxious Flayer",
		["family"] = "Wind Serpent",
		["min_level"] = 35,
		["max_level"] = 36,
		["area"] = "Dustwallow Marsh",
	},
	[4693] = {
		["attack_speed"] = 1.0,
		["name"] = "Dread Flyer",
		["family"] = "Carrion Bird",
		["min_level"] = 36,
		["max_level"] = 37,
		["area"] = "Desolace",
	},
	[4347] = {
		["attack_speed"] = 1.0,
		["name"] = "Noxious Reaver",
		["family"] = "Wind Serpent",
		["min_level"] = 37,
		["max_level"] = 38,
		["area"] = "Dustwallow Marsh",
	},
	[4348] = {
		["attack_speed"] = 1.0,
		["name"] = "Noxious Shredder",
		["family"] = "Wind Serpent",
		["min_level"] = 38,
		["max_level"] = 39,
		["area"] = "Dustwallow Marsh",
	},
	[5307] = {
		["attack_speed"] = 1.0,
		["name"] = "Vale Screecher",
		["family"] = "Wind Serpent",
		["min_level"] = 41,
		["max_level"] = 43,
		["area"] = "Feralas",
	},
	[5428] = {
		["attack_speed"] = 1.0,
		["name"] = "Roc",
		["family"] = "Carrion Bird",
		["min_level"] = 42,
		["max_level"] = 43,
		["area"] = "Tanaris",
	},
	[5429] = {
		["attack_speed"] = 1.0,
		["name"] = "Fire Roc",
		["family"] = "Carrion Bird",
		["min_level"] = 43,
		["max_level"] = 45,
		["area"] = "Tanaris",
	},
	[5308] = {
		["attack_speed"] = 1.0,
		["name"] = "Rogue Vale Screecher",
		["family"] = "Wind Serpent",
		["min_level"] = 44,
		["max_level"] = 46,
		["area"] = "Feralas",
	},
	[8207] = {
		["attack_speed"] = 1.0,
		["name"] = "Greater Firebird",
		["family"] = "Carrion Bird",
		["min_level"] = 46,
		["max_level"] = 46,
		["area"] = "Tanaris",
	},
	[5430] = {
		["attack_speed"] = 1.0,
		["name"] = "Searing Roc",
		["family"] = "Carrion Bird",
		["min_level"] = 47,
		["max_level"] = 49,
		["area"] = "Tanaris",
	},
	[7097] = {
		["attack_speed"] = 1.0,
		["name"] = "Ironbeak Owl",
		["family"] = "Owl",
		["min_level"] = 48,
		["max_level"] = 49,
		["area"] = "Felwood",
	},
	[5349] = {
		["attack_speed"] = 1.0,
		["name"] = "Arash-ethis",
		["family"] = "Wind Serpent",
		["min_level"] = 49,
		["max_level"] = 49,
		["area"] = "Feralas",
	},
	[1809] = {
		["attack_speed"] = 1.0,
		["name"] = "Carrion Vulture",
		["family"] = "Carrion Bird",
		["min_level"] = 50,
		["max_level"] = 52,
		["area"] = "Western Plaguelands",
	},
	[8299] = {
		["attack_speed"] = 1.0,
		["name"] = "Spiteflayer",
		["family"] = "Carrion Bird",
		["min_level"] = 52,
		["max_level"] = 52,
		["area"] = "Blasted Lands",
	},
	[7098] = {
		["attack_speed"] = 1.0,
		["name"] = "Ironbeak Screecher",
		["family"] = "Owl",
		["min_level"] = 52,
		["max_level"] = 53,
		["area"] = "Felwood",
	},
	[2931] = {
		["attack_speed"] = 1.0,
		["name"] = "Zaricotl",
		["family"] = "Carrion Bird",
		["min_level"] = 55,
		["max_level"] = 55,
		["area"] = "Badlands",
	},
	[17053] = {
		["attack_speed"] = 1.0,
		["name"] = "Kaliri Swooper",
		["family"] = "Owl",
		["min_level"] = 60,
		["max_level"] = 60,
		["area"] = "Hellfire Peninsula",
	},
	[17128] = {
		["attack_speed"] = 1.0,
		["name"] = "Windroc",
		["family"] = "Owl",
		["min_level"] = 64,
		["max_level"] = 65,
		["area"] = "Nagrand",
	},
	[19055] = {
		["attack_speed"] = 1.0,
		["name"] = "Windroc Matriarch",
		["family"] = "Owl",
		["min_level"] = 66,
		["max_level"] = 66,
		["area"] = "Nagrand",
	},
	[21042] = {
		["attack_speed"] = 1.0,
		["name"] = "Dire Raven",
		["family"] = "Carrion Bird",
		["min_level"] = 67,
		["max_level"] = 68,
		["area"] = "Blade's Edge Mountains",
	},
	[21804] = {
		["attack_speed"] = 1.0,
		["name"] = "Skettis Kaliri",
		["family"] = "Owl",
		["min_level"] = 70,
		["max_level"] = 70,
		["area"] = "Terokkar Forest",
	},
	[15649] = {
		["attack_speed"] = 1.0,
		["name"] = "Feral Dragonhawk Hatchling",
		["family"] = "Dragonhawk",
		["min_level"] = 5,
		["max_level"] = 6,
		["area"] = "Eversong Woods",
	},
	[15650] = {
		["attack_speed"] = 1.0,
		["name"] = "Crazed Dragonhawk",
		["family"] = "Dragonhawk",
		["min_level"] = 7,
		["max_level"] = 8,
		["area"] = "Eversong Woods",
	},
	[20502] = {
		["attack_speed"] = 1.0,
		["name"] = "Eclipsion Dragonhawk",
		["family"] = "Dragonhawk",
		["min_level"] = 67,
		["max_level"] = 68,
		["area"] = "Shadowmoon Valley",
	},
	[21864] = {
		["attack_speed"] = 1.0,
		["name"] = "Scorchshell Pincer",
		["family"] = "Scorpid",
		["min_level"] = 68,
		["max_level"] = 69,
		["area"] = "Shadowmoon Valley",
	},
	[10644] = {
		["attack_speed"] = 1.0,
		["name"] = "Mist Howler",
		["family"] = "Wolf",
		["min_level"] = 22,
		["max_level"] = 22,
		["area"] = "Ashenvale",
	},
	[2925] = {
		["attack_speed"] = 1.0,
		["name"] = "Silvermane Howler",
		["family"] = "Wolf",
		["min_level"] = 45,
		["max_level"] = 46,
		["area"] = "The Hinterlands",
	},
	[5287] = {
		["attack_speed"] = 1.0,
		["name"] = "Longtooth Howler",
		["family"] = "Wolf",
		["min_level"] = 43,
		["max_level"] = 44,
		["area"] = "Feralas",
	},
	[2924] = {
		["attack_speed"] = 1.0,
		["name"] = "Silvermane Wolf",
		["family"] = "Wolf",
		["min_level"] = 43,
		["max_level"] = 44,
		["area"] = "The Hinterlands",
	},
	[18476] = {
		["attack_speed"] = 1.0,
		["name"] = "Timber Worg",
		["family"] = "Wolf",
		["min_level"] = 62,
		["max_level"] = 63,
		["area"] = "Terokkar Forest",
	},
	[18033] = {
		["attack_speed"] = 1.0,
		["name"] = "Dark Worg",
		["family"] = "Wolf",
		["min_level"] = 64,
		["max_level"] = 65,
		["area"] = "Nagrand",
	},
	[20058] = {
		["attack_speed"] = 1.0,
		["name"] = "Bloodmaul Dire Wolf",
		["family"] = "Wolf",
		["min_level"] = 65,
		["max_level"] = 65,
		["area"] = "Blade's Edge Mountains",
	},
	[20330] = {
		["attack_speed"] = 1.0,
		["name"] = "Bloodmaul Battle Worg",
		["family"] = "Wolf",
		["min_level"] = 66,
		["max_level"] = 67,
		["area"] = "Blade's Edge Mountains",
	},
	[17527] = {
		["attack_speed"] = 1.0,
		["name"] = "Enraged Ravager",
		["family"] = "Ravager",
		["min_level"] = 16,
		["max_level"] = 17,
		["area"] = "Bloodmyst Isle",
	},
	[19189] = {
		["attack_speed"] = 1.0,
		["name"] = "Quillfang Skitterer",
		["family"] = "Ravager",
		["min_level"] = 61,
		["max_level"] = 62,
		["area"] = "Hellfire Peninsula",
	},
	[19349] = {
		["attack_speed"] = 1.0,
		["name"] = "Thornfang Ravager",
		["family"] = "Ravager",
		["min_level"] = 62,
		["max_level"] = 63,
		["area"] = "Hellfire Peninsula",
	},
	[20797] = {
		["attack_speed"] = 1.0,
		["name"] = "Deviate Coiler Hatchling",
		["family"] = "Wind Serpent",
		["min_level"] = 11,
		["max_level"] = 11,
		["area"] = "The Barrens",
	},
	[3247] = {
		["attack_speed"] = 1.0,
		["name"] = "Thunderhawk Hatchling",
		["family"] = "Wind Serpent",
		["min_level"] = 18,
		["max_level"] = 20,
		["area"] = "The Barrens",
	},
	[3424] = {
		["attack_speed"] = 1.0,
		["name"] = "Thunderhawk Cloudscraper",
		["family"] = "Wind Serpent",
		["min_level"] = 20,
		["max_level"] = 22,
		["area"] = "The Barrens",
	},
	[3249] = {
		["attack_speed"] = 1.0,
		["name"] = "Greater Thunderhawk",
		["family"] = "Wind Serpent",
		["min_level"] = 23,
		["max_level"] = 24,
		["area"] = "The Barrens",
	},
	[3472] = {
		["attack_speed"] = 1.0,
		["name"] = "Washte Pawne",
		["family"] = "Wind Serpent",
		["min_level"] = 25,
		["max_level"] = 25,
		["area"] = "The Barrens",
	},
	[4117] = {
		["attack_speed"] = 1.0,
		["name"] = "Cloud Serpent",
		["family"] = "Wind Serpent",
		["min_level"] = 25,
		["max_level"] = 26,
		["area"] = "Thousand Needles",
	},
	[4118] = {
		["attack_speed"] = 1.0,
		["name"] = "Venomous Cloud Serpent",
		["family"] = "Wind Serpent",
		["min_level"] = 26,
		["max_level"] = 28,
		["area"] = "Thousand Needles",
	},
	[4119] = {
		["attack_speed"] = 1.0,
		["name"] = "Elder Cloud Serpent",
		["family"] = "Wind Serpent",
		["min_level"] = 27,
		["max_level"] = 29,
		["area"] = "Thousand Needles",
	},
	[20749] = {
		["attack_speed"] = 1.0,
		["name"] = "Scalewing Serpent",
		["family"] = "Wind Serpent",
		["min_level"] = 66,
		["max_level"] = 67,
		["area"] = "Blade's Edge Mountains",
	},
	[21123] = {
		["attack_speed"] = 1.0,
		["name"] = "Felsworn Scalewing",
		["family"] = "Wind Serpent",
		["min_level"] = 66,
		["max_level"] = 67,
		["area"] = "Blade's Edge Mountains",
	},
	[20673] = {
		["attack_speed"] = 1.0,
		["name"] = "Swiftwing Shredder",
		["family"] = "Wind Serpent",
		["min_level"] = 68,
		["max_level"] = 69,
		["area"] = "Netherstorm",
	},
	[5224] = {
		["attack_speed"] = 1.0,
		["name"] = "Murk Slitherer",
		["family"] = "Serpent",
		["min_level"] = 45,
		["max_level"] = 46,
		["area"] = "Swamp of Sorrows",
	},
	[5225] = {
		["attack_speed"] = 1.0,
		["name"] = "Murk Spitter",
		["family"] = "Serpent",
		["min_level"] = 46,
		["max_level"] = 47,
		["area"] = "Swamp of Sorrows",
	},
	[19784] = {
		["attack_speed"] = 1.0,
		["name"] = "Coilskar Cobra",
		["family"] = "Serpent",
		["min_level"] = 68,
		["max_level"] = 68,
		["area"] = "Shadowmoon Valley",
	},
	[2406] = {
		["attack_speed"] = 1.0,
		["name"] = "Mountain Lion",
		["family"] = "Cat",
		["min_level"] = 32,
		["max_level"] = 33,
		["area"] = "Alterac Mountains",
	},
	[684] = {
		["attack_speed"] = 1.0,
		["name"] = "Shadowmaw Panther",
		["family"] = "Cat",
		["min_level"] = 37,
		["max_level"] = 38,
		["area"] = "Stranglethorn Vale",
	},
	[768] = {
		["attack_speed"] = 1.0,
		["name"] = "Shadow Panther",
		["family"] = "Cat",
		["min_level"] = 39,
		["max_level"] = 40,
		["area"] = "Swamp of Sorrows",
	},
	[3226] = {
		["attack_speed"] = 1.0,
		["name"] = "Corrupted Scorpid",
		["family"] = "Scorpid",
		["min_level"] = 10,
		["max_level"] = 11,
		["area"] = "Durotar",
	},
	[3250] = {
		["attack_speed"] = 1.0,
		["name"] = "Silithid Creeper",
		["family"] = "Scorpid",
		["min_level"] = 20,
		["max_level"] = 21,
		["area"] = "The Barrens",
	},
	[3252] = {
		["attack_speed"] = 1.0,
		["name"] = "Silithid Swarmer",
		["family"] = "Scorpid",
		["min_level"] = 21,
		["max_level"] = 22,
		["area"] = "The Barrens",
	},
	[4139] = {
		["attack_speed"] = 1.0,
		["name"] = "Scorpid Terror",
		["family"] = "Scorpid",
		["min_level"] = 33,
		["max_level"] = 34,
		["area"] = "Thousand Needles",
	},
	[4699] = {
		["attack_speed"] = 1.0,
		["name"] = "Scorpashi Venomlash",
		["family"] = "Scorpid",
		["min_level"] = 38,
		["max_level"] = 39,
		["area"] = "Desolace",
	},
	[5423] = {
		["attack_speed"] = 1.0,
		["name"] = "Scorpid Tail Lasher",
		["family"] = "Scorpid",
		["min_level"] = 43,
		["max_level"] = 44,
		["area"] = "Tanaris",
	},
	[7803] = {
		["attack_speed"] = 1.0,
		["name"] = "Scorpid Duneburrower",
		["family"] = "Scorpid",
		["min_level"] = 46,
		["max_level"] = 47,
		["area"] = "Tanaris",
	},
	[5424] = {
		["attack_speed"] = 1.0,
		["name"] = "Scorpid Dunestalker",
		["family"] = "Scorpid",
		["min_level"] = 46,
		["max_level"] = 47,
		["area"] = "Tanaris",
	},
	[5988] = {
		["attack_speed"] = 1.0,
		["name"] = "Scorpok Stinger",
		["family"] = "Scorpid",
		["min_level"] = 46,
		["max_level"] = 47,
		["area"] = "Blasted Lands",
	},
	[9691] = {
		["attack_speed"] = 1.0,
		["name"] = "Venomtip Scorpid",
		["family"] = "Scorpid",
		["min_level"] = 52,
		["max_level"] = 53,
		["area"] = "Burning Steppes",
	},
	[11735] = {
		["attack_speed"] = 1.0,
		["name"] = "Stonelash Scorpid",
		["family"] = "Scorpid",
		["min_level"] = 54,
		["max_level"] = 55,
		["area"] = "Silithus",
	},
	[11736] = {
		["attack_speed"] = 1.0,
		["name"] = "Stonelash Pincer",
		["family"] = "Scorpid",
		["min_level"] = 56,
		["max_level"] = 57,
		["area"] = "Silithus",
	},
	[9698] = {
		["attack_speed"] = 1.0,
		["name"] = "Firetail Scorpid",
		["family"] = "Scorpid",
		["min_level"] = 56,
		["max_level"] = 57,
		["area"] = "Burning Steppes",
	},
	[14476] = {
		["attack_speed"] = 1.0,
		["name"] = "Krellack",
		["family"] = "Scorpid",
		["min_level"] = 56,
		["max_level"] = 56,
		["area"] = "Silithus",
	},
	[11737] = {
		["attack_speed"] = 1.0,
		["name"] = "Stonelash Flayer",
		["family"] = "Scorpid",
		["min_level"] = 57,
		["max_level"] = 58,
		["area"] = "Silithus",
	},
	[154] = {
		["attack_speed"] = 1.0,
		["name"] = "Greater Fleshripper",
		["family"] = "Carrion Bird",
		["min_level"] = 16,
		["max_level"] = 17,
		["area"] = "Westfall",
	},
	[4158] = {
		["attack_speed"] = 1.0,
		["name"] = "Salt Flats Vulture",
		["family"] = "Carrion Bird",
		["min_level"] = 32,
		["max_level"] = 34,
		["area"] = "Thousand Needles",
	},
	[4694] = {
		["attack_speed"] = 1.0,
		["name"] = "Dread Ripper",
		["family"] = "Carrion Bird",
		["min_level"] = 39,
		["max_level"] = 40,
		["area"] = "Desolace",
	},
	[17035] = {
		["attack_speed"] = 1.0,
		["name"] = "Kaliri Matriarch",
		["family"] = "Owl",
		["min_level"] = 63,
		["max_level"] = 63,
		["area"] = "Hellfire Peninsula",
	},
	[1108] = {
		["attack_speed"] = 1.0,
		["name"] = "Mistvale Gorilla",
		["family"] = "Gorilla",
		["min_level"] = 32,
		["max_level"] = 33,
		["area"] = "Stranglethorn Vale",
	},
	[1114] = {
		["attack_speed"] = 1.0,
		["name"] = "Jungle Thunderer",
		["family"] = "Gorilla",
		["min_level"] = 37,
		["max_level"] = 38,
		["area"] = "Stranglethorn Vale",
	},
	[1557] = {
		["attack_speed"] = 1.0,
		["name"] = "Elder Mistvale Gorilla",
		["family"] = "Gorilla",
		["min_level"] = 40,
		["max_level"] = 41,
		["area"] = "Stranglethorn Vale",
	},
	[5262] = {
		["attack_speed"] = 1.0,
		["name"] = "Groddoc Thunderer",
		["family"] = "Gorilla",
		["min_level"] = 49,
		["max_level"] = 50,
		["area"] = "Feralas",
	},
	[6516] = {
		["attack_speed"] = 1.0,
		["name"] = "Un'Goro Thunderer",
		["family"] = "Gorilla",
		["min_level"] = 52,
		["max_level"] = 53,
		["area"] = "Un'Goro Crater",
	},
	[9622] = {
		["attack_speed"] = 1.0,
		["name"] = "U'cha",
		["family"] = "Gorilla",
		["min_level"] = 55,
		["max_level"] = 55,
		["area"] = "Un'Goro Crater",
	},
	[18464] = {
		["attack_speed"] = 1.0,
		["name"] = "Warp Stalker",
		["family"] = "Warp Stalker",
		["min_level"] = 63,
		["max_level"] = 64,
		["area"] = "Terokkar Forest",
	},
	[18465] = {
		["attack_speed"] = 1.0,
		["name"] = "Warp Hunter",
		["family"] = "Warp Stalker",
		["min_level"] = 64,
		["max_level"] = 65,
		["area"] = "Terokkar Forest",
	},
	[18884] = {
		["attack_speed"] = 1.0,
		["name"] = "Warp Chaser",
		["family"] = "Warp Stalker",
		["min_level"] = 67,
		["max_level"] = 68,
		["area"] = "Netherstorm",
	},
	[23219] = {
		["attack_speed"] = 1.0,
		["name"] = "Blackwind Warp Chaser",
		["family"] = "Warp Stalker",
		["min_level"] = 69,
		["max_level"] = 70,
		["area"] = "Terokkar Forest",
	},
}
